name: Go

on:
  pull_request:
    branches: [ master ]

env:
  GO111MODULE: "on"
  GOPROXY: "https://proxy.golang.org"
  working-directory: .

jobs:

  go_get:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: go get
        run: cd /tmp && go get "github.com/${GITHUB_REPOSITORY}"

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Check out code
        uses: actions/checkout@v2

      - name: Linters
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.33
          working-directory: ${{env.working-directory}}

      - name: Makefile
        run: |
          make lint
        working-directory: ${{env.working-directory}}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod download
        working-directory: ${{env.working-directory}}

      - name: build
        run: |
          make build
        working-directory: ${{env.working-directory}}

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod download
        working-directory: ${{env.working-directory}}

      - name: Unit tests
        run: |
          make test
        working-directory: ${{env.working-directory}}

  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod download
        working-directory: ${{env.working-directory}}

      - name: Makefile
        run: |
          make integration-test
        working-directory: ${{env.working-directory}}